using System.Diagnostics;
using Microsoft.CodeAnalysis;

namespace Puppet.Generator;

[Generator]
public class PuppetGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
#if DEBUG
        if (!Debugger.IsAttached)
        {
            Debugger.Launch();
        }
#endif  
    }

    public void Execute(GeneratorExecutionContext context)
    {
         // Find the main method
        var mainMethod = context.Compilation.GetEntryPoint(context.CancellationToken);

        // Build up the source code
        string source = $@"// <auto-generated/>
using System;

namespace Foo 
{{
    public static class FooClass
    {{
        public static void HelloFrom(string name) =>
            Console.WriteLine($""Generator says: Hi from '{{name}}'"");
    }}
}}
";
        var typeName = mainMethod.ContainingType.Name;

        // Add the source code to the compilation
        context.AddSource($"{typeName}.g.cs", source);
    }
}